# Generated by Django 2.1.12 on 2019-11-13 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=50, verbose_name='列名')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='标题')),
                ('column_en_name', models.CharField(max_length=50, verbose_name='英文名')),
                ('parameter', models.CharField(blank=True, max_length=10, null=True, verbose_name='参数名')),
                ('formula', models.CharField(blank=True, max_length=100, null=True, verbose_name='公式')),
                ('dropdown', models.CharField(blank=True, max_length=10, null=True, verbose_name='下拉列表')),
                ('default', models.CharField(blank=True, max_length=100, null=True, verbose_name='默认值')),
                ('prompt', models.CharField(blank=True, max_length=100, null=True, verbose_name='提示')),
                ('must', models.BooleanField(default=True, verbose_name='是否必填')),
                ('aggregate', models.CharField(blank=True, choices=[('SUM', 'SUM'), ('MAX', 'MAX'), ('AVG', 'AVG')], max_length=10, null=True, verbose_name='合计方式')),
                ('type', models.CharField(choices=[('text', 'text'), ('checkbox', 'checkbox')], default='text', max_length=10, verbose_name='类型')),
                ('width', models.IntegerField(default=100, verbose_name='列宽度')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50, verbose_name='模块名')),
                ('module_en_name', models.CharField(max_length=50, verbose_name='英文模块名')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have', models.CharField(choices=[('是', '是'), ('否', '否')], default='否', max_length=2)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('project_num', models.CharField(max_length=20, verbose_name='项目编号')),
                ('project_text', models.TextField(verbose_name='项目概况')),
                ('designer', models.CharField(max_length=50, verbose_name='设计人')),
                ('proofreader', models.CharField(max_length=50, verbose_name='校对人')),
                ('chief', models.CharField(max_length=50, verbose_name='专业负责人')),
                ('approver', models.CharField(max_length=50, verbose_name='审批人')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50, verbose_name='表名')),
                ('table_en_name', models.CharField(max_length=50, verbose_name='英文名')),
                ('catalog', models.CharField(max_length=50, verbose_name='所属模块')),
                ('subtitle1', models.CharField(blank=True, max_length=50, null=True, verbose_name='小标题一')),
                ('subtitle2', models.CharField(blank=True, max_length=50, null=True, verbose_name='小标题二')),
                ('total', models.CharField(blank=True, max_length=20, null=True, verbose_name='合计')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField(blank=True, null=True, verbose_name='第几行')),
                ('value', models.TextField(verbose_name='值')),
                ('formula', models.TextField(blank=True, null=True, verbose_name='公式')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Column')),
                ('project_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firefightwater.ProjectTable')),
            ],
        ),
        migrations.AddField(
            model_name='projecttable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Table'),
        ),
        migrations.AddField(
            model_name='moduletable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Table'),
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Table'),
        ),
    ]
