# Generated by Django 2.1.12 on 2019-09-27 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=50, verbose_name='列名')),
                ('column_en_name', models.CharField(max_length=50, verbose_name='英文名')),
                ('parameter', models.CharField(max_length=10, null=True, verbose_name='参数名')),
                ('formula', models.CharField(max_length=100, null=True, verbose_name='公式')),
                ('dropdown', models.CharField(max_length=10, null=True, verbose_name='下拉列表')),
                ('default', models.CharField(max_length=10, null=True, verbose_name='默认值')),
                ('prompt', models.CharField(max_length=100, null=True, verbose_name='提示')),
                ('must', models.BooleanField(default=True, verbose_name='是否必填')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('project_num', models.CharField(max_length=20, verbose_name='项目编号')),
                ('project_text', models.TextField(verbose_name='项目概况')),
                ('designer', models.CharField(max_length=50, verbose_name='设计人')),
                ('proofreader', models.CharField(max_length=50, verbose_name='校对人')),
                ('chief', models.CharField(max_length=50, verbose_name='专业负责人')),
                ('approver', models.CharField(max_length=50, verbose_name='审批人')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50, verbose_name='表名')),
                ('table_en_name', models.CharField(max_length=50, verbose_name='英文名')),
                ('catalog', models.CharField(max_length=50, verbose_name='所属模块')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='值')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('project_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firefightwater.ProjectTable')),
            ],
        ),
        migrations.AddField(
            model_name='projecttable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Table'),
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Table'),
        ),
    ]
