# Generated by Django 2.1.12 on 2019-09-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefightwater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='subtitle',
            field=models.CharField(max_length=50, null=True, verbose_name='小标题'),
        ),
    ]
