# Generated by Django 2.1.12 on 2019-09-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefightwater', '0002_table_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='table',
            name='subtitle1',
            field=models.CharField(max_length=50, null=True, verbose_name='小标题一'),
        ),
        migrations.AddField(
            model_name='table',
            name='subtitle2',
            field=models.CharField(max_length=50, null=True, verbose_name='小标题二'),
        ),
    ]
