# Generated by Django 2.1.12 on 2019-09-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefightwater', '0003_auto_20190927_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='default',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='默认值'),
        ),
        migrations.AlterField(
            model_name='column',
            name='dropdown',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='下拉列表'),
        ),
        migrations.AlterField(
            model_name='column',
            name='formula',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公式'),
        ),
        migrations.AlterField(
            model_name='column',
            name='parameter',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='参数名'),
        ),
        migrations.AlterField(
            model_name='column',
            name='prompt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='提示'),
        ),
        migrations.AlterField(
            model_name='table',
            name='subtitle1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='小标题一'),
        ),
        migrations.AlterField(
            model_name='table',
            name='subtitle2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='小标题二'),
        ),
    ]
