# Generated by Django 2.1.12 on 2019-09-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefightwater', '0004_auto_20190927_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='default',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='默认值'),
        ),
    ]
