# Generated by Django 2.1.12 on 2019-10-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefightwater', '0005_auto_20190930_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='标题'),
        ),
    ]
