# Generated by Django 2.1.12 on 2019-10-16 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firefightwater', '0006_column_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50, verbose_name='模块名')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Module')),
                ('Table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Table')),
            ],
        ),
        migrations.AddField(
            model_name='projecttable',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Module'),
            preserve_default=False,
        ),
    ]
