# Generated by Django 2.1.12 on 2019-10-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefightwater', '0007_auto_20191016_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduletable',
            old_name='Module',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='moduletable',
            old_name='Table',
            new_name='table',
        ),
        migrations.AddField(
            model_name='module',
            name='module_en_name',
            field=models.CharField(default=1, max_length=50, verbose_name='英文模块名'),
            preserve_default=False,
        ),
    ]
