# Generated by Django 2.2.4 on 2019-10-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefightwater', '0008_auto_20191016_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletable',
            name='have',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default='否', max_length=2),
        ),
    ]
