# Generated by Django 2.2.4 on 2019-11-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefightwater', '0011_auto_20191110_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('checkbox', 'checkbox')], default='text', max_length=10, verbose_name='类型'),
        ),
    ]
