# Generated by Django 2.2.4 on 2019-11-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firefightwater', '0012_auto_20191110_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firefightwater.Column'),
        ),
        migrations.AddField(
            model_name='value',
            name='line',
            field=models.IntegerField(blank=True, null=True, verbose_name='第几行'),
        ),
    ]
