# Generated by Django 2.2.4 on 2019-11-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefightwater', '0013_auto_20191110_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='formula',
            field=models.TextField(blank=True, null=True, verbose_name='公式'),
        ),
    ]
